version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-node-modules-{{ checksum "package-lock.json" }}
          - v1-node-modules-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-node-modules-{{ checksum "package-lock.json" }}

      - run: npm run test
