name: CI
on: push

jobs:
  check:
    name: Check with Node.js ${{ matrix.node-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['8', '9']
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        if: matrix.node-version != '9'
        run: npm ci

      - name: Install dependencies
        if: matrix.node-version == '9'
        run: npm install

      - name: Check code formatting
        run: npm run format-check

      - name: Lint code
        run: npm run lint

      - name: Run tests
        run: npm run test
